/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.user;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author BlossomVixen
 */
public class RegisterDialog extends javax.swing.JDialog {

    /**
     * Creates new form RegisterDialog
     */
    ArrayList<User> users; // All users will be stored here 
    public RegisterDialog(java.awt.Frame parent, boolean modal, ArrayList<User> users) {
        super(parent, modal);
        initComponents();
        this.users = users; //needed to verify duplicate emails
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RegisterBTN = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        emailInput.setBackground(new java.awt.Color(204, 255, 204));
        emailInput.setForeground(new java.awt.Color(0, 0, 0));
        emailInput.setText("email");
        emailInput.setToolTipText("");

        passwordInput.setBackground(new java.awt.Color(204, 255, 204));
        passwordInput.setForeground(new java.awt.Color(0, 0, 0));
        passwordInput.setText("password");
        passwordInput.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("E-Mail:");

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Password:");

        nameInput.setBackground(new java.awt.Color(204, 255, 204));
        nameInput.setForeground(new java.awt.Color(0, 0, 0));
        nameInput.setText("name");

        jLabel3.setText("Name:");

        RegisterBTN.setBackground(new java.awt.Color(153, 255, 51));
        RegisterBTN.setForeground(new java.awt.Color(0, 0, 0));
        RegisterBTN.setText("Register");
        RegisterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameInput)
                            .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(RegisterBTN)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        
    private void WriteOnFile(User u)
    {
        String v = "!abcdefghijklmnopqrstuvwxyz1"; // so even if it's public, other methods can't get the info
        
        try{
            FileWriter writer = new FileWriter("users.txt", true); // boolean true is to avoid overwriting the file each time
            writer.write(u.getInfo(v));
            writer.close();
        } catch (IOException ioe) { JOptionPane.showMessageDialog(null, "Something went wrong"); }
    }
    private void RegisterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBTNActionPerformed
        // TODO add your handling code here:
        
        String email = emailInput.getText();
        //thanks to these two booleans, I'm also checking whether the strign is empty or not 
        boolean isHatPresent = false; 
        boolean isDotPresent = false;
        for(int i = 0; i < email.length(); i++) // checking for @ and the '.' (dot)
        {
            if(email.charAt(i) == '@') isHatPresent = true;
            if(email.charAt(i) == '.') isDotPresent = true;
        } // should check if there are multiple @ or dots, but I want to keep it simple
        if(!isHatPresent || !isDotPresent){ JOptionPane.showMessageDialog(null, "e-mail is invalid");}
        
        boolean isEmailDupe = false;
        for(int i = 0; i < users.size(); i++)
        {
            if(email.equals(users.get(i).getEMail())) isEmailDupe = true;
        }
        if(isEmailDupe) JOptionPane.showMessageDialog(null, "Email already registered. Log in instead");
        boolean isEmailValid = isHatPresent && isDotPresent && !isEmailDupe; // for better readability
        
        String password = passwordInput.getText();
        boolean isPasswordValid = false; // true if >= 8 characters
        if(password.length() >= 8) isPasswordValid = true;
        if(!isPasswordValid) JOptionPane.showMessageDialog(null, "Password is too short. (minimum: 8)");
        
        String name = nameInput.getText();
        boolean isNameValid = false; // true if >= 5 characters
        if(name.length() >= 5) isNameValid = true;
        if(!isNameValid) JOptionPane.showMessageDialog(null, "Name is too short. (minimum: 5)");
        
        boolean valid = isEmailValid && isPasswordValid && isNameValid;
        if(valid)
        {
            User u = new User(name, email, password);
            users.add(u);
            WriteOnFile(u);
            JOptionPane.showMessageDialog(null, "Your account has been succesfully created. Please Close this window and return to the log-in page.");
            
        }
    }//GEN-LAST:event_RegisterBTNActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton RegisterBTN;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField passwordInput;
    // End of variables declaration//GEN-END:variables
}
